version: '3'
services:
  web:
    image: pokerhands_web:latest
    build: ./PokerHands.Web
    ports:
     - "80:80"
     - "3000:3000"
  api:
    image: pokerhands_api:latest
    build: ./PokerHands.API
    ports:
     - "5000:80"